### ISSUE TITLE
网站访问不了!

### ISSUE THREAD

**Issue by zhangyyysss** [jeffwcx/translate-smacss-zh#8]
网站访问不了!

**Comment by jeffwcx** [comment]
Vercel的原因，我晚点在gitee上放一份吧

**Comment by jeffwcx** [comment]
@zhangyyysss 你现在处于什么地区呀？我现在看了下全国的访问速率，好像都还可以啊

**Comment by zhangyyysss** [comment]
> @zhangyyysss 你现在处于什么地区呀？我现在看了下全国的访问速率，好像都还可以啊

已经可以正常访问了~谢谢,我是深圳
